name: safe_diary
description: "My First Biz"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get: ^4.7.2
  http: ^1.4.0
  intl: ^0.20.2
  crypto: ^3.0.6
  flutter_svg_provider:
  firebase_core: ^3.13.0
  flutter_dotenv: ^5.2.1
  table_calendar: ^3.1.3
  cupertino_icons: ^1.0.8
  naver_login_sdk: ^3.0.2
  web_socket_client: ^0.2.0
  firebase_messaging: ^15.2.5
  kakao_flutter_sdk: ^1.9.7+3
  flutter_secure_storage: ^9.2.4
  flutter_local_notifications: ^19.2.1
  no_screenshot: ^0.3.1
  stomp_dart_client: ^2.1.3
  crystal_navigation_bar: ^1.0.4
  firebase_analytics: ^11.4.6
  omni_datetime_picker: ^2.1.1
  flex_color_scheme: ^8.2.0
  flutter_native_splash: ^2.4.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/weather/
    - lib/app/config/

# --- flutter_native_splash ---
flutter_native_splash:
  background_image: "assets/home_light_back.png"
  background_image_dark: "assets/home_dark_back.png"

  android_12:
    color: "#F4F3F9"
    color_dark: "#141233"

  fullscreen: true

# --- flutter_launcher_icons ---
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21